# Generated by Django 5.2.7 on 2025-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_trackinghistory_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
