# Generated by Django 5.2.7 on 2025-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackinghistory_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
